import type { Product, Show, User, Rating, Notification, Clip } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 129.99,
    image: "/wireless-headphones.png",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery",
    sellerId: "seller1",
    sellerName: "TechHub",
    category: "Electronics",
    stock: 25,
  },
  {
    id: "2",
    name: "Designer Sunglasses",
    price: 199.99,
    image: "/designer-sunglasses.png",
    description: "Stylish UV-protected designer sunglasses with polarized lenses",
    sellerId: "seller2",
    sellerName: "Fashion Forward",
    category: "Fashion",
    stock: 15,
  },
  {
    id: "3",
    name: "Smart Watch Pro",
    price: 299.99,
    image: "/smartwatch-lifestyle.png",
    description: "Advanced fitness tracking with heart rate monitor and GPS navigation",
    sellerId: "seller1",
    sellerName: "TechHub",
    category: "Electronics",
    stock: 30,
  },
  {
    id: "4",
    name: "Luxury Perfume Set",
    price: 89.99,
    image: "/elegant-perfume-bottle.png",
    description: "Premium fragrance collection with 3 exclusive scents",
    sellerId: "seller3",
    sellerName: "Beauty Essentials",
    category: "Beauty",
    stock: 40,
  },
  {
    id: "5",
    name: "Portable Bluetooth Speaker",
    price: 79.99,
    image: "/bluetooth-speaker.jpg",
    description: "360-degree sound with waterproof design and 20-hour battery",
    sellerId: "seller1",
    sellerName: "TechHub",
    category: "Electronics",
    stock: 20,
  },
  {
    id: "6",
    name: "Silk Pillowcase Set",
    price: 49.99,
    image: "/silk-pillowcase.png",
    description: "Luxurious silk pillowcases for hair and skin health with hypoallergenic materials",
    sellerId: "seller3",
    sellerName: "Beauty Essentials",
    category: "Home",
    stock: 50,
  },
  {
    id: "7",
    name: "Leather Messenger Bag",
    price: 159.99,
    image: "/leather-bag.png",
    description: "Premium genuine leather messenger bag with multiple compartments",
    sellerId: "seller2",
    sellerName: "Fashion Forward",
    category: "Fashion",
    stock: 18,
  },
  {
    id: "8",
    name: "4K Webcam",
    price: 149.99,
    image: "/webcam-4k.png",
    description: "Professional 4K webcam with auto-focus and noise-cancelling microphone",
    sellerId: "seller1",
    sellerName: "TechHub",
    category: "Electronics",
    stock: 22,
  },
  {
    id: "9",
    name: "Organic Face Serum",
    price: 65.99,
    image: "/face-serum.png",
    description: "Natural organic face serum with vitamins and antioxidants",
    sellerId: "seller3",
    sellerName: "Beauty Essentials",
    category: "Beauty",
    stock: 35,
  },
  {
    id: "10",
    name: "Cashmere Sweater",
    price: 189.99,
    image: "/cashmere-sweater.png",
    description: "Premium cashmere sweater in multiple colors with luxury finish",
    sellerId: "seller2",
    sellerName: "Fashion Forward",
    category: "Fashion",
    stock: 12,
  },
]

export const mockClips: Clip[] = [
  {
    id: "clip-1",
    thumbnail: "/wireless-headphones.png",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    title: "These headphones are insane! 🎧",
    hostName: "Tech Reviewer",
    hostAvatar: "/tech-expert-host.jpg",
    productId: "1",
    views: 1205,
    likes: 342,
  },
  {
    id: "clip-2",
    thumbnail: "/designer-sunglasses.png",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    title: "Summer style must-haves ☀️",
    hostName: "Fashion Icon",
    hostAvatar: "/fashion-stylist-host.jpg",
    productId: "2",
    views: 892,
    likes: 156,
  },
  {
    id: "clip-3",
    thumbnail: "/smartwatch-lifestyle.png",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    title: "Track your fitness like a pro 💪",
    hostName: "Fitness Guru",
    hostAvatar: "/tech-expert-host.jpg",
    productId: "3",
    views: 2341,
    likes: 890,
  },
]

export const mockShows: Show[] = [
  {
    id: "show1",
    title: "Tech Gadgets Live Shopping",
    description: "Discover the latest tech gadgets with exclusive deals on electronics",
    image: "/tech-gadgets-showcase.jpg",
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    hostId: "host1",
    hostName: "Sarah Tech",
    hostAvatar: "/placeholder-user.jpg",
    featured: true,
    viewerCount: 2845,
    status: "scheduled",
    category: "Technology",
    tags: ["gadgets", "tech", "deals"],
    products: ["1", "3", "5", "8"],
    maxViewers: 5000,
    streamId: "stream_tech_gadgets_show1",
    hlsUrl: "http://localhost:5080/app/streams/stream_tech_gadgets_show1.m3u8",
    dashUrl: "http://localhost:5080/app/streams/stream_tech_gadgets_show1.mpd",
    rtmpUrl: "rtmp://localhost:5080/app/",
  },
  {
    id: "show2",
    title: "Beauty Trends & Makeup Tutorial",
    description: "Learn makeup tips from beauty experts with live shopping",
    image: "/beauty-makeup-tutorial.jpg",
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
    hostId: "host2",
    hostName: "Jessica Beauty",
    hostAvatar: "/placeholder-user.jpg",
    featured: true,
    viewerCount: 1623,
    status: "scheduled",
    category: "Beauty",
    tags: ["makeup", "beauty", "tutorial"],
    products: ["4", "9"],
    maxViewers: 3000,
    streamId: "stream_beauty_tutorial_show2",
    hlsUrl: "http://localhost:5080/app/streams/stream_beauty_tutorial_show2.m3u8",
    dashUrl: "http://localhost:5080/app/streams/stream_beauty_tutorial_show2.mpd",
    rtmpUrl: "rtmp://localhost:5080/app/",
  },
  {
    id: "show3",
    title: "Fashion Week Special Collection",
    description: "Exclusive fashion pieces from emerging designers",
    image: "/fashion-collection-showcase.png",
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
    hostId: "host3",
    hostName: "Mike Fashion",
    hostAvatar: "/placeholder-user.jpg",
    featured: false,
    status: "scheduled",
    category: "Fashion",
    tags: ["fashion", "style", "designers"],
    products: ["2", "7", "10"],
    maxViewers: 4000,
    streamId: "stream_fashion_show3",
    hlsUrl: "http://localhost:5080/app/streams/stream_fashion_show3.m3u8",
    dashUrl: "http://localhost:5080/app/streams/stream_fashion_show3.mpd",
    rtmpUrl: "rtmp://localhost:5080/app/",
  },
  {
    id: "show4",
    title: "Home Comfort Essentials",
    description: "Transform your living space with premium home essentials",
    image: "/home-essentials.jpg",
    startTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
    hostId: "host4",
    hostName: "Alex Home",
    hostAvatar: "/placeholder-user.jpg",
    featured: false,
    status: "scheduled",
    category: "Home",
    tags: ["home", "comfort", "lifestyle"],
    products: ["6"],
    maxViewers: 2500,
    streamId: "stream_home_show4",
    hlsUrl: "http://localhost:5080/app/streams/stream_home_show4.m3u8",
    dashUrl: "http://localhost:5080/app/streams/stream_home_show4.mpd",
    rtmpUrl: "rtmp://localhost:5080/app/",
  },
  {
    id: "show5",
    title: "Professional Tech Setup Guide",
    description: "Complete guide to building your perfect tech workspace",
    image: "/tech-setup.jpg",
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    hostId: "host1",
    hostName: "Sarah Tech",
    hostAvatar: "/placeholder-user.jpg",
    featured: true,
    status: "ended",
    category: "Technology",
    tags: ["tech", "setup", "productivity"],
    products: ["1", "3", "5", "8"],
    maxViewers: 3500,
    streamId: "stream_tech_setup_show5",
    hlsUrl: "http://localhost:5080/app/streams/stream_tech_setup_show5.m3u8",
    dashUrl: "http://localhost:5080/app/streams/stream_tech_setup_show5.mpd",
    rtmpUrl: "rtmp://localhost:5080/app/",
  },
]

export const mockUsers: User[] = [
  {
    id: "user1",
    name: "Sarah Chen",
    email: "sarah@example.com",
    avatar: "/user-avatar-1.jpg",
    bio: "Tech enthusiast & product reviewer",
    followers: 1250,
    following: 342,
    isFollowing: false,
    role: "seller",
  },
  {
    id: "user2",
    name: "Alex Martinez",
    email: "alex@example.com",
    avatar: "/user-avatar-2.jpg",
    bio: "Fashion blogger & style expert",
    followers: 3450,
    following: 180,
    isFollowing: false,
    role: "seller",
  },
  {
    id: "user3",
    name: "Jordan Lee",
    email: "jordan@example.com",
    avatar: "/user-avatar-3.jpg",
    bio: "Gaming & electronics specialist",
    followers: 2100,
    following: 520,
    isFollowing: false,
    role: "buyer",
  },
  {
    id: "user4",
    name: "Emma Wilson",
    email: "emma@example.com",
    avatar: "/user-avatar-4.jpg",
    bio: "Beauty and lifestyle curator",
    followers: 5600,
    following: 280,
    isFollowing: true,
    role: "seller",
  },
  {
    id: "admin1",
    name: "Super Admin",
    email: "admin@jbliveshopping.com",
    avatar: "/placeholder-user.jpg",
    bio: "Platform Administrator",
    followers: 0,
    following: 0,
    isFollowing: false,
    role: "admin",
  },
]

export const mockRatings: Rating[] = [
  {
    id: "rating1",
    userId: "user1",
    userName: "Sarah Chen",
    userAvatar: "/user-avatar-1.jpg",
    score: 5,
    title: "Amazing quality!",
    comment: "Better than expected. Highly recommend!",
    productId: "1",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    helpful: 24,
  },
  {
    id: "rating2",
    userId: "user2",
    userName: "Alex Martinez",
    userAvatar: "/user-avatar-2.jpg",
    score: 4,
    title: "Great product",
    comment: "Good quality, delivery was fast",
    productId: "1",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    helpful: 18,
  },
  {
    id: "rating3",
    userId: "user3",
    userName: "Jordan Lee",
    userAvatar: "/user-avatar-3.jpg",
    score: 5,
    title: "Perfect!",
    comment: "Exactly what I was looking for",
    productId: "2",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    helpful: 12,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    type: "follow",
    title: "New follower",
    message: "Emma Wilson started following you",
    userId: "user4",
    read: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: "notif2",
    type: "show_starting",
    title: "Show starting soon",
    message: "Fashion styling consultation starts in 30 minutes",
    targetId: "show2",
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: "notif3",
    type: "restock",
    title: "Product back in stock",
    message: "Wireless Earbuds Pro is now available",
    targetId: "1",
    read: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
]
